#! /bin/bash

packages=(
  curl
  emacs
  git
  htop
  imagemagick
  manpages
  screen
  wget
)

# Support for running in containers
SUDO="sudo"
[[ $EUID -eq 0 ]] && SUDO=""

if which apt >& /dev/null; then
  echo "Using apt"
  $SUDO apt update
  pkgs_to_install=""
  for pkg in ${packages[@]}; do
    if apt show $pkg >& /dev/null; then
      pkgs_to_install="$pkgs_to_install $pkg"
    else
      echo "Unable to find $pkg, skipping..."
    fi
  done
  echo "Installing $pkgs_to_install"
  $SUDO apt install -y $pkgs_to_install
elif which yum >& /dev/null; then
  echo "Using yum"
fi
