; Time-stamp: <2019-03-23 08:44:19 josh>

;; Custom vars from emacs configure
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-PDF-mode t)
 '(appt-display-duration 55)
 '(appt-display-interval 1)
 '(archive-superior-buffer nil t)
 '(auto-compression-mode t nil (jka-compr))
 '(bar-cursor 2)
 '(calendar-mark-diary-entries-flag t)
 '(case-fold-search t)
 '(column-number-mode t)
 '(comint-completion-addsuffix t)
 '(comint-completion-autolist t)
 '(comint-input-ignoredups t)
 '(comint-move-point-for-output t)
 '(comint-scroll-to-bottom-on-input t)
 '(current-language-environment "UTF-8")
 '(custom-enabled-themes (quote (misterioso)))
 '(custom-safe-themes
   (quote
    ("a1e99cb36d6235abbe426a0a96fc26c006306f6b9d2a64c2435363350a987b4c" default)))
 '(default-frame-alist
    (quote
     ((background-color . "Black")
      (foreground-color . "White")
      (cursor-color . "red")
      (width . 120)
      (height . 42)
      (vertical-scroll-bars)
      (horizontal-scroll-bars))))
 '(default-input-method "rfc1345")
 '(delete-selection-mode t nil (delsel))
 '(diary-file "~/.emacs.d/diary")
 '(diff-mode-hook (quote (view-mode)))
 '(dired-copy-preserve-time t)
 '(dired-keep-marker-copy 67)
 '(display-time-mode t)
 '(ecb-options-version "2.40")
 '(european-calendar-style t)
 '(f90-do-indent 2)
 '(f90-if-indent 2)
 '(f90-type-indent 2)
 '(focus-follows-mouse t)
 '(fortran-line-length 131)
 '(fortran-structure-indent 2)
 '(fortran-tab-mode-default nil t)
 '(gdb-find-source-frame t)
 '(gdb-show-main t)
 '(gdb-use-colon-colon-notation t)
 '(global-auto-revert-ignore-buffer nil t)
 '(global-font-lock-mode t nil (font-lock))
 '(grep-find-command "find -L . -type f -print0 | xargs -0 -e grep -nG -e ")
 '(ibuffer-always-compile-formats nil)
 '(ido-mode (quote both) nil (ido))
 '(ido-save-directory-list-file "~/.emacs.d/ido.last")
 '(imaxima-fnt-size "Large")
 '(imaxima-pt-size 12)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-frame-alist
   (quote
    ((background-color . "Black")
     (foreground-color . "White")
     (cursor-color . "red")
     (width . 120)
     (height . 42)
     (vertical-scroll-bars)
     (horizontal-scroll-bars))))
 '(iswitchb-mode t)
 '(kill-whole-line t)
 '(latex-run-command "pdflatex")
 '(lazy-highlight-cleanup nil)
 '(mark-diary-entries-in-calendar t)
 '(minibuffer-message-timeout 2 t)
 '(mouse-buffer-menu-maxlen 30)
 '(mouse-buffer-menu-mode-mult 10)
 '(mouse-wheel-follow-mouse t)
 '(mouse-wheel-mode t nil (mwheel))
 '(mouse-wheel-progressive-speed nil)
 '(msb-max-menu-items 30)
 '(next-line-add-newlines nil)
 '(org-clock-history-length 10)
 '(org-clock-into-drawer "LOGBOOK")
 '(org-clock-modeline-total (quote today))
 '(org-clock-persist (quote today))
 '(org-enforce-todo-checkbox-dependencies t)
 '(org-enforce-todo-dependencies t)
 '(org-journal-dir "~/.emacs.d/journal/")
 '(org-link-frame-setup
   (quote
    ((vm . vm-visit-folder-other-frame)
     (gnus . gnus-other-frame)
     (file . find-file))))
 '(org-log-done nil)
 '(org-log-note-clock-out nil)
 '(org-return-follows-link t)
 '(package-selected-packages (quote (helm which-key markdown-mode)))
 '(ps-bottom-margin 36)
 '(py-block-comment-prefix "# ")
 '(python-mode-hook (quote (imenu-add-menubar-index)) t)
 '(require-final-newline t)
 '(safe-local-variable-values
   (quote
    ((eval replace-string "||" "|" 1 -100)
     (eval setq p2
           (point))
     (eval skip-chars-forward "Local variables")
     (eval add-hook
           (quote write-file-hooks)
           (quote time-stamp)))))
 '(save-place t nil (saveplace))
 '(save-place-file "~/.emacs.d/emacs-places")
 '(save-place-limit 50)
 '(scroll-conservatively 1)
 '(send-mail-function (quote sendmail-send-it))
 '(sh-basic-offset 2)
 '(sh-indentation 2)
 '(shell-command-default-error-buffer nil t)
 '(show-paren-mode t nil (paren))
 '(show-paren-style (quote expression))
 '(show-trailing-whitespace nil)
 '(tab-width 4)
 '(tags-add-tables (quote ask-user))
 '(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify)))
 '(tool-bar-mode nil)
 '(trace-buffer "*trace-output*")
 '(track-mouse nil t)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(vc-make-backup-files t)
 '(vc-svn-deff-switches "-x-bw")
 '(view-read-only t)
 '(visible-bell t)
 '(whitespace-style
   (quote
    (tabs trailing lines-tail space-before-tab empty space-after-tab tab-mark))))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "Black" :foreground "White" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 160 :width normal :foundry "unknown" :family "Monospace"))))
 '(fringe ((t (:background "gray10"))))
 '(scroll-bar ((t (:background "grey" :foreground "#000000"))))
 '(show-paren-match ((t (:background "grey20"))))
 '(trailing-whitespace ((((class color) (background dark)) (:background "orange")))))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
